LOCAL_PATH := vendor/onda/v989
PRODUCT_COPY_FILES += \
$(LOCAL_PATH)/system/bin/wpa_supplicant:system/bin/wpa_supplicant \
$(LOCAL_PATH)/system/etc/powervr.ini:system/etc/powervr.ini \
$(LOCAL_PATH)/system/etc/camera.cfg:system/etc/camera.cfg \
$(LOCAL_PATH)/system/etc/bluetooth/auto_pair_devlist.conf:system/etc/bluetooth/auto_pair_devlist.conf \
$(LOCAL_PATH)/system/etc/bluetooth/bt_did.conf:system/etc/bluetooth/bt_did.conf \
$(LOCAL_PATH)/system/etc/bluetooth/bt_stack.conf:system/etc/bluetooth/bt_stack.conf \
$(LOCAL_PATH)/system/etc/bluetooth/bt_vendor.conf:system/etc/bluetooth/bt_vendor.conf \
$(LOCAL_PATH)/system/etc/wifi/p2p_supplicant_overlay.conf:system/etc/wifi/p2p_supplicant_overlay.conf \
$(LOCAL_PATH)/system/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
$(LOCAL_PATH)/system/etc/wifi/wpa_supplicant_overlay.conf:system/etc/wifi/wpa_supplicant_overlay.conf \
$(LOCAL_PATH)/system/lib/libEGL.so:system/lib/libEGL.so \
$(LOCAL_PATH)/system/lib/libGLES_trace.so:system/lib/libGLES_trace.so \
$(LOCAL_PATH)/system/lib/libIMGegl.so:system/vendor/lib/libIMGegl.so \
$(LOCAL_PATH)/system/lib/libOmxCore.so:system/lib/libOmxCore.so \
$(LOCAL_PATH)/system/lib/libOmxVdec.so:system/lib/libOmxVdec.so \
$(LOCAL_PATH)/system/lib/libOmxVenc.so:system/lib/libOmxVenc.so \
$(LOCAL_PATH)/system/lib/libGLESv1_CM.so:system/lib/libGLESv1_CM.so \
$(LOCAL_PATH)/system/lib/libGLESv2.so:system/lib/libGLESv2.so \
$(LOCAL_PATH)/system/lib/libGLESv3.so:system/lib/libGLESv3.so \
$(LOCAL_PATH)/system/lib/libpower.so:system/lib/libpower.so \
$(LOCAL_PATH)/system/lib/libOpenSLES.so:system/lib/libOpenSLES.so \
$(LOCAL_PATH)/system/lib/libpvrANDROID_WSEGL.so:system/vendor/lib/libpvrANDROID_WSEGL.so \
$(LOCAL_PATH)/system/lib/libPVROCL.so:system/vendor/lib/libPVROCL.so \
$(LOCAL_PATH)/system/lib/libPVRScopeServices.so:system/vendor/lib/libPVRScopeServices.so \
$(LOCAL_PATH)/system/lib/libsrv_init.so:system/vendor/lib/libsrv_init.so \
$(LOCAL_PATH)/system/lib/libsrv_um.so:system/vendor/lib/libsrv_um.so \
$(LOCAL_PATH)/system/lib/libufwriter.so:system/vendor/lib/libufwriter.so \
$(LOCAL_PATH)/system/lib/libusc.so:system/vendor/lib/libusc.so \
$(LOCAL_PATH)/system/lib/egl/egl.cfg:system/lib/egl/egl.cfg \
$(LOCAL_PATH)/system/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
$(LOCAL_PATH)/system/lib/egl/libEGL_POWERVR_ROGUE.so:system/vendor/lib/egl/libEGL_POWERVR_ROGUE.so \
$(LOCAL_PATH)/system/lib/egl/libGLESv1_CM_POWERVR_ROGUE.so:system/vendor/lib/egl/libGLESv1_CM_POWERVR_ROGUE.so \
$(LOCAL_PATH)/system/lib/egl/libEGL_POWERVR_ROGUE.so:system/vendor/lib/egl/libEGL_POWERVR_ROGUE.so \
$(LOCAL_PATH)/system/lib/egl/libGLESv2_POWERVR_ROGUE.so:system/vendor/lib/egl/libGLESv2_POWERVR_ROGUE.so \
$(LOCAL_PATH)/system/lib/hw/audio.primary.kylin.so:system/lib/hw/audio.primary.kylin.so \
$(LOCAL_PATH)/system/lib/hw/camera.kylin.so:system/lib/hw/camera.kylin.so \
$(LOCAL_PATH)/system/lib/hw/lights.kylin.so:system/lib/hw/lights.kylin.so \
$(LOCAL_PATH)/system/lib/hw/hwcomposer.kylin.so:system/lib/hw/hwcomposer.kylin.so \
$(LOCAL_PATH)/system/lib/hw/sensors.kylin.so:system/lib/hw/sensors.kylin.so \
$(LOCAL_PATH)/system/lib/hw/keystore.kylin.so:system/lib/hw/keystore.kylin.so \
$(LOCAL_PATH)/system/lib/hw/gralloc.sun9i.so:system/vendor/lib/hw/gralloc.sun9i.so \
$(LOCAL_PATH)/system/usr/idc/tp.idc:system/usr/idc/tp.idc \
$(LOCAL_PATH)/system/usr/gsensor.cfg:system/usr/gsensor.cfg \
$(LOCAL_PATH)/system/usr/keylayout/AVRCP.kl:system/usr/keylayout/AVRCP.kl \
$(LOCAL_PATH)/system/usr/keylayout/Generic.kl:system/usr/keylayout/Generic.kl \
$(LOCAL_PATH)/system/usr/keylayout/sunxi-ir.kl:system/usr/keylayout/sunxi-ir.kl \
$(LOCAL_PATH)/system/usr/keylayout/sunxi-keyboard.kl:system/usr/keylayout/sunxi-keyboard.kl \
$(LOCAL_PATH)/system/modules/gt9xx_ts.ko:system/vendor/modules/gt9xx_ts.ko \
$(LOCAL_PATH)/system/modules/gt9xxf_ts.ko:system/vendor/modules/gt9xxf_ts.ko \
$(LOCAL_PATH)/system/modules/gt9xxnew_ts.ko:system/vendor/modules/gt9xxnew_ts.ko \
$(LOCAL_PATH)/system/modules/gt82x.ko:system/vendor/modules/gt82x.ko \
$(LOCAL_PATH)/system/modules/gt818_ts.ko:system/vendor/modules/gt82x.ko \
$(LOCAL_PATH)/system/modules/gt2005.ko:system/vendor/modules/gt2005.ko \
$(LOCAL_PATH)/system/modules/lcd.ko:system/vendor/modules/lcd.ko \
$(LOCAL_PATH)/system/modules/nand.ko:system/vendor/modules/nand.ko \
$(LOCAL_PATH)/system/modules/nvram.txt:system/vendor/modules/nvram.txt \
$(LOCAL_PATH)/system/modules/sunxi_dma_test.ko:system/vendor/modules/sunxi_dma_test.ko \
$(LOCAL_PATH)/system/modules/sunxi_fd.ko:system/vendor/modules/sunxi_fd.ko \
$(LOCAL_PATH)/system/modules/sunxi_gmac.ko:system/vendor/modules/sunxi_gmac.ko \
$(LOCAL_PATH)/system/modules/sunxi_pinctrl_test.ko:system/vendor/modules/sunxi_pinctrl_test.ko \
$(LOCAL_PATH)/system/modules/sunxi_schw.ko:system/vendor/modules/sunxi_schw.ko \
$(LOCAL_PATH)/system/modules/sunxi_timer_test.ko:system/vendor/modules/sunxi_timer_test.ko \
$(LOCAL_PATH)/system/modules/sunxi-ir-rx.ko:system/vendor/modules/sunxi-ir-rx.ko \
$(LOCAL_PATH)/system/modules/sunxi-ir-tx.ko:system/vendor/modules/sunxi-ir-tx.ko \
$(LOCAL_PATH)/system/modules/sunxi-led.ko:system/vendor/modules/sunxi-led.ko \
$(LOCAL_PATH)/system/modules/sunxi-vibrator.ko:system/vendor/modules/sunxi-vibrator.ko \
$(LOCAL_PATH)/system/modules/videobuf-core.ko:system/vendor/modules/videobuf-core.ko \
$(LOCAL_PATH)/system/modules/videobuf-dma-contig.ko:system/vendor/modules/videobuf-dma-contig.ko 



